---
abstract: 'Test for and flip the taint flag without regex matches or C<eval>'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Taint-Util
no_index:
  directory:
    - t
requires:
  Taint::Util: 0
  Test::More: 0
  XSLoader: 0
resources:
  Ratings: http://cpanratings.perl.org/d/Taint-Util
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Taint-Util
  homepage: http://search.cpan.org/dist/Taint-Util/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/avar/taint-util
version: 0.07
