--- #YAML:1.0
name:                Taint-Util
version:             0.06
abstract:            Test for and flip the taint flag without regex matches or C<eval>
license:             perl
author:              
    - Ævar Arnfjörð Bjarmason <avar@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
