abstract: Test and flip the taint flag on scalars without regex matches or C<eval>
author: "\xC3\x86var Arnfj\xC3\xB6r\xC3\xB0 Bjarmason <avar@cpan.org>"
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Taint-Util
no_index: 
  directory: 
    - inc
    - t
requires: 
  Exporter: 0
  XSLoader: 0
tests: t/*.t
